version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18          # Using Node.js 18 for compatibility
    commands:
      - echo "Installing dependencies..."
      - npm install       # Install Node.js dependencies

  build:
    commands:
      - echo "No build step required for static files."

  post_build:
    commands:
      - echo "Build phase completed successfully."

artifacts:
  files:
    - public/**/*         # Frontend static files (HTML, CSS)
    - server.js           # Backend entry point
    - package.json        # For dependency management
    - package-lock.json   # Locks dependencies for consistency
    - .gitignore          # Optional but good for completeness
    - README.md           # Documentation (optional)
  discard-paths: no
